apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: auth-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017"
        - name: DATABASE_NAME
          value: "auth_db"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "1"
        - name: REFRESH_TOKEN_EXPIRE_DAYS
          value: "7"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret-key
        - name: ALGORITHM
          value: "HS256"
        - name: PORT
          value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  secret-key: your-secret-key-for-jwt 